### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by gw2princeps** [discretize/react-discretize-components#4]
- [ ] fix first-child pseudo class (replace with first-of-type) 
- [x] update theme
- [x] revenant legends component not respecting sizes
- [x] fix bad padding in character component
